FROM continuumio/miniconda3:4.10.3

RUN apt-get --allow-releaseinfo-change update && apt-get install --fix-missing  libgl1-mesa-glx procps -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN git clone https://github.com/BayraktarLab/feature_reg.git /opt/feature_reg
RUN conda update conda && conda env update -n base --file /opt/feature_reg/environment.yml
RUN python3 -m pip install --upgrade pip fire dask_image --no-cache-dir
