FROM continuumio/miniconda3:4.10.3

RUN apt-get --allow-releaseinfo-change update && apt-get install --fix-missing  libgl1-mesa-glx procps -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN python3 -m pip install --upgrade pip \
	fire \
	pysnooper \
	--no-cache-dir
ADD microaligner /src/microaligner
RUN cd /src/microaligner && pip install -e .
