channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - scikit-image
  - dask
  - pip
  - pip:
    - ome-types
    - ome-zarr
    - opencv-contrib-python==4.5.5.62
    - tifffile
    - bigstream
    - fire
